import test from 'node:test';
import assert from 'node:assert/strict';
import {levels, initialPositions, crossRiver, bankError} from '../engine.js';
function solve(level){const ids=levels[level].people.map(p=>p.id);const key=(p,s)=>ids.map(id=>p[id]).join('')+s;const initial=initialPositions(level);const queue=[{positions:initial,side:0,path:[]}],seen=new Set([key(initial,0)]);for(let n=0;n<queue.length;n++){const state=queue[n],available=ids.filter(id=>state.positions[id]===state.side);const options=available.flatMap((id,i)=>[[id],...available.slice(i+1).map(other=>[id,other])]);for(const passengers of options){const r=crossRiver(level,state.positions,state.side,passengers);if(r.error)continue;const path=[...state.path,passengers];if(r.won)return path;const k=key(r.positions,r.side);if(!seen.has(k)){seen.add(k);queue.push({...r,path});}}}return null;}
for(let i=0;i<levels.length;i++)test(`LEVEL ${i+1}: shortest solution and replay`,()=>{const path=solve(i);assert.ok(path,'must be solvable');assert.equal(path.length,[3,7,11,11,17][i]);let p=initialPositions(i),s=0;for(const passengers of path){const original={...p};const r=crossRiver(i,p,s,passengers);assert.ok(!r.error);assert.deepEqual(p,original,'must not mutate input');p=r.positions;s=r.side;for(const bank of [0,1])assert.equal(bankError(i,Object.keys(p).filter(id=>p[id]===bank)),'');}assert.ok(Object.values(p).every(side=>side===1));console.log(`LEVEL ${i+1}: ${path.length} moves verified`);});
test('empty, capacity, operator and wrong-bank guards',()=>{assert.match(crossRiver(0,initialPositions(0),0,[]).error,/乗せ/);assert.match(crossRiver(0,initialPositions(0),0,['apple']).error,/農夫/);assert.match(crossRiver(0,initialPositions(0),0,['farmer','apple','pumpkin']).error,/定員/);assert.ok(crossRiver(0,initialPositions(0),1,['farmer']).error);assert.ok(crossRiver(0,initialPositions(0),0,['farmer','farmer']).error);assert.match(crossRiver(4,initialPositions(4),0,['son1','dog']).error,/父・母・メイド/);});
test('wolf, goat and cabbage hazards',()=>{assert.match(bankError(1,['wolf','goat']),/狼がヤギ/);assert.match(bankError(1,['goat','cabbage']),/ヤギがキャベツ/);assert.equal(bankError(1,['farmer','wolf','goat','cabbage']),'');assert.equal(bankError(1,['wolf','cabbage']),'');});
test('couple rule for every pair',()=>{for(const g of ['A','B','C']){const other=g==='A'?'B':'A';assert.ok(bankError(2,['w'+g,'h'+other]));assert.equal(bankError(2,['w'+g,'h'+g,'h'+other]),'');}assert.equal(bankError(2,['wA','wB','wC']),'');});
test('population rule includes zero missionaries exception',()=>{assert.equal(bankError(3,['c1','c2','c3']),'');assert.equal(bankError(3,['m1','m2','c1','c2']),'');assert.ok(bankError(3,['m1','c1','c2']));});
test('family supervision and dog',()=>{assert.ok(bankError(4,['father','daughter1']));assert.ok(bankError(4,['mother','son2']));assert.ok(bankError(4,['dog','son1']));assert.equal(bankError(4,['father','mother','son1','daughter2']),'');assert.equal(bankError(4,['maid','dog','son1']),'');assert.equal(bankError(4,['dog']),'');});
test('arrival shore is validated as well as departure',()=>{const p={farmer:0,wolf:1,goat:1,cabbage:0};assert.ok(crossRiver(1,p,0,['farmer']).positions);const couples={hA:1,wA:1,hB:0,wB:0,hC:0,wC:0};assert.ok(crossRiver(2,couples,0,['wB']).error);});
